const mongoose = require('mongoose');

const UserSchema = mongoose.Schema({
    firstName: String,
    lastName: String,
    contactAddress: String,
    permanentAddress: String,
    gender: String,
    dateOfBirth: String,
    maritalStatus: String,
    phoneNumber: String,
    nic: String,
    fatherName: String,
    motherName: String,
    spouseName: String,
    childrenNumber: String,
    stateOfOrigin: String,
    lga: String,
    dateOfJoin: String,
    dateOfConf: String,
    idNumber: String,
    password: String,
    nextOfKFirstName: String,
    nextOfKLastName: String,
    nextOfKContactAddress: String,
    nextOfKPermanentAddress: String,
    nextOfKGender: String,
    nextOfKDateOfBirth: String,
    nextOfKMaritalStatus: String,
    nextofKReligion: String,
    nextOfKPhone: String,
    nextOfKNIC: String,
    nextOfKFatherName: String,
    nextOfKMotherName: String,
    nextOfKSpouse: String,
    nextOfKChildrenNumber: String,
    nextOfKState: String,
    nextOfKLGA: String,
    oLevel: String,
    aLevel: String,
    sports: String,
    otherSkills: String,
    salary: Number,
    bank: String,
    accountNumber: String,
    deduction: Number,
    sortCode: String,
    duration: Number,
    gratuity: Number,
    pension: Number,
    paid: {
        type: String,
        default: 'Not paid'
    }
});

let User = module.exports = mongoose.model('User', UserSchema); 